### ISSUE TITLE
When updating to version v1.3.50.3, it crashes with an error

### ISSUE THREAD

**Issue by timurgum** [multiversx/mx-chain-mainnet-config#160]
`elrond.node2         | ERROR   bootstrapDataComponentsFactory create() failed: shard id must be smaller than the total number of shards`

**Comment by schimih** [comment]
Hey @timurgum ,
Do you still have this problem?
Did you update to latest versions?

**Comment by schimih** [comment]
I will close this issue just because in the meantime we are at v1.4.8 preparing for 1.5.0 :muscle:
