### ISSUE TITLE
docker image missing v1.6.18.0

### ISSUE THREAD

**Issue by YuXiaoCoder** [multiversx/mx-chain-mainnet-config#199]

**Comment by bogdan-rosianu** [comment]
Might be an outdated issue? the image is published 17 days ago: 
https://hub.docker.com/layers/multiversx/chain-mainnet/v1.6.18.0/images/sha256-b1b9c7bfc1ced06dfd2e496c2217d6d3b967056f51386d355bc13d9297cc3a46?context=explore
